services:
  - type: web
    name: agrimitra
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
